name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v3

      - uses: Homebrew/actions/setup-homebrew@master
        id: set-up-homebrew

      - uses: gradle/wrapper-validation-action@v1
      - run: brew install libpq

      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 11

      - run: ./gradlew assemble

      - run: ./gradlew build

      - uses: actions/upload-artifact@v3
        with:
          path: |
            build/reports/tests
            testing/build/reports/tests
        if: failure()