name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.parallel=false -Dorg.gradle.jvmargs="-Xmx5g -XX:+UseParallelGC -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    strategy:
      matrix:
        os: [ 'macos-latest', 'ubuntu-latest' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup Homebrew
        uses: Homebrew/actions/setup-homebrew@master
        id: set-up-homebrew

      - name: Install libpq
        run: brew install libpq

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 11

      - name: Setup Postgres
        uses: ikalnytskyi/action-setup-postgres@v3

      - name: build
        run: ./gradlew build

      - name: Upload test reports
        uses: actions/upload-artifact@v3
        with:
          path: |
            build/reports/tests
            testing/build/reports/tests
        if: failure()
